# Generated by Django 6.0.5 on 2026-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('content', models.TextField(verbose_name='বিস্তারিত খবর')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='খবরের ছবি')),
                ('source', models.CharField(default='Admin', max_length=100, verbose_name='খবরের উৎস')),
                ('is_published', models.BooleanField(default=True, verbose_name='প্রকাশিত?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='প্রকাশের সময়')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'নিউজ পোস্ট',
                'verbose_name_plural': 'নিউজ পোস্টসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
