# Generated by Django 6.0.5 on 2026-05-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='প্রতিবেদক/রিপোর্টার'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('pending', 'অপেক্ষমান (Pending)'), ('approved', 'অনুমোদিত (Approved)'), ('rejected', 'বাতিল (Rejected)')], default='pending', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='রিপোর্ট জমার সময়'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='প্রকাশিত?'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='source',
            field=models.CharField(default='নিজস্ব প্রতিবেদক', max_length=100, verbose_name='খবরের উৎস'),
        ),
    ]
