# Generated by Django 6.0.5 on 2026-05-11 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspost_author_newspost_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_news', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to=settings.AUTH_USER_MODEL, verbose_name='প্রতিবেদক/রিপোর্টার'),
        ),
    ]
