# Generated by Django 6.0.5 on 2026-05-11 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_approved_by_alter_newspost_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('edit', 'এডিট করা হয়েছে (Edited)'), ('status_change', 'স্ট্যাটাস পরিবর্তন (Status Changed)')], max_length=20, verbose_name='ধরণ')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='পুরানো স্ট্যাটাস')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='নতুন স্ট্যাটাস')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='পরিবর্তনের বিবরণ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='সময়')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='news.newspost', verbose_name='নিউজ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ব্যবহারকারী')),
            ],
            options={
                'verbose_name': 'এডিট হিস্ট্রি',
                'verbose_name_plural': 'এডিট হিস্ট্রি',
                'ordering': ['-created_at'],
            },
        ),
    ]
