# Generated by Django 6.0.5 on 2026-05-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsedithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ক্যাটাগরি নাম')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='স্লাগ')),
            ],
            options={
                'verbose_name': 'ক্যাটাগরি',
                'verbose_name_plural': 'ক্যাটাগরি সমূহ',
            },
        ),
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='news.category', verbose_name='ক্যাটাগরি'),
        ),
    ]
