# Generated by Django 6.0.5 on 2026-05-12 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_newspost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='সংবাদ প্রতিষ্ঠানের নাম'),
        ),
        migrations.CreateModel(
            name='ReporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ভেরিফাইড?')),
                ('organization', models.CharField(blank=True, max_length=150, null=True, verbose_name='সংবাদ প্রতিষ্ঠান')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'রিপোর্টার প্রোফাইল',
                'verbose_name_plural': 'রিপোর্টার প্রোফাইল সমূহ',
            },
        ),
    ]
