# Generated by Django 6.0.5 on 2026-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newspost_organization_name_reporterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='প্রোফাইল ছবি'),
        ),
        migrations.AddField(
            model_name='reporterprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='পরিচিতি'),
        ),
    ]
