# Generated by Django 6.0.5 on 2026-05-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_reporterprofile_avatar_reporterprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='রক্তের গ্রুপ')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন নম্বর')),
                ('location', models.CharField(max_length=150, verbose_name='অবস্থান')),
                ('is_available', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'রক্তদাতা',
                'verbose_name_plural': 'রক্তদাতাসমূহ',
                'ordering': ['blood_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200, verbose_name='রুটের নাম')),
                ('departure_time', models.TimeField(verbose_name='ছাড়ার সময়')),
                ('bus_type', models.CharField(default='Regular', max_length=50, verbose_name='বাসের ধরন (AC/Non-AC)')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ভাড়া (টাকা)')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'বাস সময়সূচি',
                'verbose_name_plural': 'বাস সময়সূচিসমূহ',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ডাক্তারের নাম')),
                ('specialty', models.CharField(max_length=150, verbose_name='বিশেষজ্ঞতা')),
                ('degree', models.CharField(max_length=200, verbose_name='ডিগ্রি')),
                ('location', models.CharField(max_length=200, verbose_name='হাসপাতাল / ক্লিনিক')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='ফোন')),
                ('is_available', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ডাক্তার',
                'verbose_name_plural': 'ডাক্তারসমূহ',
                'ordering': ['specialty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='শিরোনাম')),
                ('number', models.CharField(max_length=30, verbose_name='নম্বর')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='বিবরণ')),
                ('icon', models.CharField(default='phone', max_length=50, verbose_name='আইকন (lucide)')),
                ('color_hex', models.CharField(default='#1d4ed8', max_length=10, verbose_name='রঙ (Hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
            ],
            options={
                'verbose_name': 'জরুরি যোগাযোগ',
                'verbose_name_plural': 'জরুরি যোগাযোগসমূহ',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='পদের নাম')),
                ('company', models.CharField(max_length=150, verbose_name='প্রতিষ্ঠান')),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=20, verbose_name='চাকরির ধরন')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('location', models.CharField(max_length=200, verbose_name='অবস্থান')),
                ('deadline', models.DateField(verbose_name='আবেদনের শেষ তারিখ')),
                ('apply_link', models.URLField(blank=True, verbose_name='আবেদনের লিংক')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'চাকরির বিজ্ঞপ্তি',
                'verbose_name_plural': 'চাকরির বিজ্ঞপ্তিসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='নাম')),
                ('description', models.TextField(verbose_name='বিবরণ')),
                ('image_url', models.URLField(blank=True, verbose_name='ছবির URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourist_spots/', verbose_name='ছবি আপলোড')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='অবস্থান')),
                ('map_link', models.URLField(blank=True, verbose_name='ম্যাপ লিংক')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ক্রম')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'পর্যটন স্থান',
                'verbose_name_plural': 'পর্যটন স্থানসমূহ',
                'ordering': ['order', 'title'],
            },
        ),
    ]
