# Generated by Django 6.0.5 on 2026-05-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_complaint_educationinstitution_governmentservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='নাম (EN/BN)')),
                ('icon', models.CharField(default='globe', help_text='Lucide icon name', max_length=50)),
                ('color_hex', models.CharField(default='#1d4ed8', max_length=10)),
                ('route_type', models.CharField(choices=[('tab', 'Bottom Tab'), ('screen', 'Screen Navigation')], default='screen', max_length=20)),
                ('target', models.CharField(help_text='Index for tab (0-3) or Screen Name for screen', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'হোম সার্ভিস আইকন',
                'verbose_name_plural': 'হোম সার্ভিস আইকনসমূহ',
                'ordering': ['order'],
            },
        ),
    ]
