# Generated by Django 6.0.5 on 2026-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_homeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Police', 'Police'), ('Fire', 'Fire Service'), ('Hospital', 'Hospital'), ('Ambulance', 'Ambulance')], default='General', max_length=50, verbose_name='ধরণ'),
        ),
    ]
