# Generated by Django 6.0.5 on 2026-05-12 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_emergencycontact_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='বিজ্ঞাপনের শিরোনাম')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='বিজ্ঞাপন ছবি')),
                ('link', models.URLField(blank=True, null=True, verbose_name='লিংক (ঐচ্ছিক)')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'বিজ্ঞাপন',
                'verbose_name_plural': 'বিজ্ঞাপনসমূহ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='হাসপাতালের নাম')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='ঠিকানা')),
                ('specialized_services', models.CharField(blank=True, default='', help_text='ICU, NICU, Dialysis etc.', max_length=500, verbose_name='বিশেষ সেবা')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ফোন নম্বর')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospitals/', verbose_name='ছবি')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ভেরিফাইড?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'হাসপাতাল',
                'verbose_name_plural': 'হাসপাতালসমূহ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blooddonor',
            options={'verbose_name': 'রক্তদাতা', 'verbose_name_plural': 'রক্তদাতাসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'সংবাদ ক্যাটাগরি', 'verbose_name_plural': 'সংবাদ ক্যাটাগরিসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'অভিযোগ', 'verbose_name_plural': 'অভিযোগসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'ডাক্তার', 'verbose_name_plural': 'ডাক্তারগণ'},
        ),
        migrations.AlterModelOptions(
            name='educationinstitution',
            options={'verbose_name': 'শিক্ষা প্রতিষ্ঠান', 'verbose_name_plural': 'শিক্ষা প্রতিষ্ঠানসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='governmentservice',
            options={'verbose_name': 'সরকারি সেবা', 'verbose_name_plural': 'সরকারি সেবাসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='homeservice',
            options={'ordering': ['order'], 'verbose_name': 'হোম সার্ভিস', 'verbose_name_plural': 'হোম সার্ভিসসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='newsedithistory',
            options={'verbose_name': 'নিউজ এডিট ইতিহাস', 'verbose_name_plural': 'নিউজ এডিট ইতিহাসসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-created_at'], 'verbose_name': 'সংবাদ', 'verbose_name_plural': 'সংবাদসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='professionalservice',
            options={'verbose_name': 'পেশাজীবী সেবা', 'verbose_name_plural': 'পেশাজীবী সেবাসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='reporterprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='blooddonor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='homeservice',
            name='color_hex',
        ),
        migrations.RemoveField(
            model_name='homeservice',
            name='route_type',
        ),
        migrations.RemoveField(
            model_name='homeservice',
            name='target',
        ),
        migrations.RemoveField(
            model_name='homeservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='newsedithistory',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='newsedithistory',
            name='changes',
        ),
        migrations.RemoveField(
            model_name='newsedithistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newsedithistory',
            name='old_status',
        ),
        migrations.RemoveField(
            model_name='newsedithistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True, verbose_name='শেষ রক্তদানের তারিখ'),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='সেবার নাম'),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='target_screen',
            field=models.CharField(blank=True, max_length=100, verbose_name='টার্গেট স্ক্রিন'),
        ),
        migrations.AddField(
            model_name='newsedithistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsedithistory',
            name='edited_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newsedithistory',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsedithistory',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='এভেইল্যাবল?'),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='দাতার নাম'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ছাড়ার সময়'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ভাড়া (টাকা)'),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='route_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='রুটের নাম'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(blank=True, choices=[('Electricity', 'বিদ্যুৎ'), ('Water', 'পানি'), ('Roads', 'রাস্তাঘাট'), ('Waste', 'বর্জ্য'), ('Other', 'অন্যান্য')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=200, verbose_name='চেম্বার/হাসপাতাল'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ডাক্তারের নাম'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='ফোন (ঐচ্ছিক)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='বিশেষজ্ঞ'),
        ),
        migrations.AlterField(
            model_name='educationinstitution',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary School'), ('High School', 'High School'), ('College', 'College'), ('University', 'University'), ('Madrasa', 'Madrasa'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationinstitution',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationinstitution',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationinstitution',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='governmentservice',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='governmentservice',
            name='icon',
            field=models.CharField(default='globe', max_length=50),
        ),
        migrations.AlterField(
            model_name='governmentservice',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='governmentservice',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='homeservice',
            name='icon',
            field=models.CharField(default='wrench', max_length=50, verbose_name='আইকন'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200, verbose_name='কোম্পানি'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(verbose_name='ডেডলাইন'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full Time', max_length=50, verbose_name='ধরণ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, verbose_name='পদবি'),
        ),
        migrations.AlterField(
            model_name='newsedithistory',
            name='new_status',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newsedithistory',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='news.newspost'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='লেখক'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='ক্যাটাগরি'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.TextField(verbose_name='বিস্তারিত সংবাদ'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='সংস্থার নাম'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='উৎস'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='অবস্থা'),
        ),
        migrations.AlterField(
            model_name='professionalservice',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ক্যাটাগরি (উদা: ইলেকট্রিশিয়ান, মেকানিক)'),
        ),
        migrations.AlterField(
            model_name='professionalservice',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='এখন পাওয়া যাবে?'),
        ),
        migrations.AlterField(
            model_name='professionalservice',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ঠিকানা/এলাকা'),
        ),
        migrations.AlterField(
            model_name='professionalservice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='professionalservice',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ফোন নম্বর'),
        ),
        migrations.AlterField(
            model_name='reporterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='reporterprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reporterprofile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='নিউজ অর্গানাইজেশন'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='বিবরণ'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='ছবির URL'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='অবস্থান'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='map_link',
            field=models.URLField(blank=True, default='', verbose_name='ম্যাপ লিংক'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='নাম'),
        ),
    ]
