# Generated by Django 6.0.5 on 2026-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_advertisement_hospital_alter_blooddonor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blooddonor',
            options={'ordering': ['-created_at'], 'verbose_name': 'রক্তদাতা', 'verbose_name_plural': 'রক্তদাতাসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'অভিযোগ', 'verbose_name_plural': 'অভিযোগসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at'], 'verbose_name': 'ডাক্তার', 'verbose_name_plural': 'ডাক্তারগণ'},
        ),
        migrations.AlterModelOptions(
            name='educationinstitution',
            options={'ordering': ['-created_at'], 'verbose_name': 'শিক্ষা প্রতিষ্ঠান', 'verbose_name_plural': 'শিক্ষা প্রতিষ্ঠানসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='governmentservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'সরকারি সেবা', 'verbose_name_plural': 'সরকারি সেবাসমূহ'},
        ),
        migrations.AlterModelOptions(
            name='professionalservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'পেশাজীবী সেবা', 'verbose_name_plural': 'পেশাজীবী সেবাসমূহ'},
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='educationinstitution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
