# Generated by Django 6.0.5 on 2026-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_blooddonor_options_alter_complaint_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeservice',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='homeservice',
            name='target_screen',
        ),
        migrations.AddField(
            model_name='homeservice',
            name='color_hex',
            field=models.CharField(default='#3b82f6', max_length=10, verbose_name='রঙ (Hex)'),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='route_type',
            field=models.CharField(choices=[('screen', 'Screen'), ('tab', 'Tab')], default='screen', max_length=20),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='target',
            field=models.CharField(blank=True, max_length=100, verbose_name='টার্গেট (Screen Name or Tab Index)'),
        ),
        migrations.AlterField(
            model_name='homeservice',
            name='icon',
            field=models.CharField(default='wrench', max_length=50, verbose_name='আইকন (Lucide)'),
        ),
    ]
