# Generated by Django 6.0.5 on 2026-05-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_rename_name_homeservice_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admob_enabled', models.BooleanField(default=True, verbose_name='Google AdMob চালু?')),
            ],
            options={
                'verbose_name': 'অ্যাপ সেটিংস',
                'verbose_name_plural': 'অ্যাপ সেটিংস',
            },
        ),
    ]
