# Generated by Django 6.0.5 on 2026-05-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_appconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='ক্লিকসমূহ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='শেষের তারিখ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='শুরুর তারিখ'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='ইমপ্রেশন (Views)'),
        ),
    ]
