# Generated by Django 6.0.5 on 2026-05-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_advertisement_clicks_advertisement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='বেশি হলে অ্যাড আগে দেখাবে', verbose_name='প্রায়োরিটি'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_views',
            field=models.PositiveIntegerField(default=0, help_text='০ দিলে আনলিমিটেড', verbose_name='টার্গেট ইমপ্রেশন'),
        ),
    ]
