# Generated by Django 6.0.5 on 2026-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_advertisement_priority_advertisement_target_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='ad_carousel_interval',
            field=models.PositiveIntegerField(default=5, help_text='বিজ্ঞাপন কত সেকেন্ড পর পর পরিবর্তন হবে', verbose_name='অ্যাড ক্যারোসেল বিরতি (সেকেন্ড)'),
        ),
    ]
