# Generated by Django 6.0.5 on 2026-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_appconfiguration_ad_carousel_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='admob_frequency',
            field=models.PositiveIntegerField(default=3, help_text='কতটি লোকাল অ্যাড দেখানোর পর অ্যাডমোব শো করবে (যদি মিক্সড মোডে থাকে)', verbose_name='অ্যাডমোব ফ্রিকোয়েন্সি'),
        ),
    ]
