# Generated by Django 6.0.5 on 2026-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_appconfiguration_admob_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentservice',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='govt_services/', verbose_name='লোগো/ছবি'),
        ),
    ]
