# Generated by Django 6.0.5 on 2026-05-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_governmentservice_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='is_admob_enabled',
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='is_admob_enabled_global',
            field=models.BooleanField(default=True, verbose_name='গ্লোবাল AdMob চালু?'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_blood',
            field=models.BooleanField(default=True, verbose_name='Blood Bank: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_complaint',
            field=models.BooleanField(default=True, verbose_name='Complaint: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_directory',
            field=models.BooleanField(default=True, verbose_name='Directory: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_doctor',
            field=models.BooleanField(default=True, verbose_name='Doctor: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_education',
            field=models.BooleanField(default=True, verbose_name='Education: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_emergency',
            field=models.BooleanField(default=True, verbose_name='Emergency: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_government',
            field=models.BooleanField(default=True, verbose_name='Government: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_home',
            field=models.BooleanField(default=True, verbose_name='Home: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_hospital',
            field=models.BooleanField(default=True, verbose_name='Hospital: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_job_board',
            field=models.BooleanField(default=True, verbose_name='Job Board: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_news',
            field=models.BooleanField(default=True, verbose_name='News: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_professional',
            field=models.BooleanField(default=True, verbose_name='Professional: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_tourist',
            field=models.BooleanField(default=True, verbose_name='Tourist: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_transport',
            field=models.BooleanField(default=True, verbose_name='Transport: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_blood',
            field=models.BooleanField(default=True, verbose_name='Blood Bank: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_complaint',
            field=models.BooleanField(default=True, verbose_name='Complaint: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_directory',
            field=models.BooleanField(default=True, verbose_name='Directory: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_doctor',
            field=models.BooleanField(default=True, verbose_name='Doctor: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_education',
            field=models.BooleanField(default=True, verbose_name='Education: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_emergency',
            field=models.BooleanField(default=True, verbose_name='Emergency: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_government',
            field=models.BooleanField(default=True, verbose_name='Government: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_home',
            field=models.BooleanField(default=True, verbose_name='Home: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_hospital',
            field=models.BooleanField(default=True, verbose_name='Hospital: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_job_board',
            field=models.BooleanField(default=True, verbose_name='Job Board: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_news',
            field=models.BooleanField(default=True, verbose_name='News: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_professional',
            field=models.BooleanField(default=True, verbose_name='Professional: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_tourist',
            field=models.BooleanField(default=True, verbose_name='Tourist: Local Ads'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_transport',
            field=models.BooleanField(default=True, verbose_name='Transport: Local Ads'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='ad_carousel_interval',
            field=models.PositiveIntegerField(default=5, verbose_name='অ্যাড ক্যারোসেল বিরতি (সেকেন্ড)'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='admob_frequency',
            field=models.PositiveIntegerField(default=3, verbose_name='অ্যাডমোব ফ্রিকোয়েন্সি'),
        ),
    ]
