# Generated by Django 6.0.5 on 2026-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_advertisement_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='is_local_ads_enabled_global',
            field=models.BooleanField(default=True, verbose_name='গ্লোবাল লোকাল অ্যাড চালু?'),
        ),
    ]
