# Generated by Django 6.0.5 on 2026-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_appconfiguration_is_local_ads_enabled_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_breaking',
            field=models.BooleanField(default=False, verbose_name='ব্রেকিং নিউজ?'),
        ),
    ]
