# Generated by Django 6.0.5 on 2026-05-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_newspost_is_breaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='breaking_type',
            field=models.CharField(default='BREAKING', max_length=50, verbose_name='ব্রেকিং টাইপ (উদা: বিজ্ঞপ্তি, ঘোষণা)'),
        ),
    ]
