# Generated by Django 6.0.5 on 2026-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_newspost_breaking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_global_banner',
            field=models.BooleanField(default=True, verbose_name='Global Banner: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_global_banner',
            field=models.BooleanField(default=True, verbose_name='Global Banner: Local Ads'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(help_text='সেরা ফলাফলের জন্য ৬০০x১০০ পিক্সেল (আড়াআড়ি) সাইজের ইমেজ ব্যবহার করুন।', upload_to='ads/', verbose_name='বিজ্ঞাপন ছবি'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='breaking_type',
            field=models.CharField(default='BREAKING', max_length=50, verbose_name='ব্রেকিং টাইপ'),
        ),
    ]
