# Generated by Django 6.0.5 on 2026-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_appconfiguration_show_admob_global_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='show_admob_global_banner',
        ),
        migrations.RemoveField(
            model_name='appconfiguration',
            name='show_local_global_banner',
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_global_bottom',
            field=models.BooleanField(default=True, verbose_name='Global Bottom: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_global_bottom',
            field=models.BooleanField(default=True, verbose_name='Global Bottom: Local Ads'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('all', 'সব পেজ (All)'), ('home', 'হোম পেজ (Home)'), ('news', 'নিউজ পেজ (News)'), ('emergency', 'জরুরি সেবা (Emergency)'), ('directory', 'ডিরেক্টরি (Directory)'), ('hospital', 'হাসপাতাল (Hospital)'), ('professional', 'পেশাজীবী সেবা (Professional)'), ('job_board', 'জব বোর্ড (Jobs)'), ('blood', 'রক্তদান (Blood)'), ('complaint', 'অভিযোগ (Complaint)'), ('education', 'শিক্ষা প্রতিষ্ঠান (Education)'), ('global_bottom', 'গ্লোবাল বটম ব্যানার (Global Bottom)')], default='all', max_length=50, verbose_name='অ্যাড প্লেসমেন্ট'),
        ),
    ]
