# Generated by Django 6.0.5 on 2026-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_remove_appconfiguration_show_admob_global_bottom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('all', 'সব পেজ (All)'), ('home', 'হোম পেজ (Home)'), ('news', 'নিউজ পেজ (News)'), ('emergency', 'জরুরি সেবা (Emergency)'), ('directory', 'ডিরেক্টরি (Directory)'), ('hospital', 'হাসপাতাল (Hospital)'), ('professional', 'পেশাজীবী সেবা (Professional)'), ('job_board', 'জব বোর্ড (Jobs)'), ('blood', 'রক্তদান (Blood)'), ('complaint', 'অভিযোগ (Complaint)'), ('education', 'শিক্ষা প্রতিষ্ঠান (Education)'), ('footer', 'Footer Banner (Global Bottom)')], default='all', max_length=50, verbose_name='অ্যাড প্লেসমেন্ট'),
        ),
    ]
