# Generated by Django 6.0.5 on 2026-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_alter_advertisement_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='show_admob_footer',
        ),
        migrations.RemoveField(
            model_name='appconfiguration',
            name='show_local_footer',
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_admob_site_footer',
            field=models.BooleanField(default=True, verbose_name='Site Footer: AdMob'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='show_local_site_footer',
            field=models.BooleanField(default=True, verbose_name='Site Footer: Local Ads'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('all', 'সব পেজ (All)'), ('home', 'হোম পেজ (Home)'), ('news', 'নিউজ পেজ (News)'), ('emergency', 'জরুরি সেবা (Emergency)'), ('directory', 'ডিরেক্টরি (Directory)'), ('hospital', 'হাসপাতাল (Hospital)'), ('professional', 'পেশাজীবী সেবা (Professional)'), ('job_board', 'জব বোর্ড (Jobs)'), ('blood', 'রক্তদান (Blood)'), ('complaint', 'অভিযোগ (Complaint)'), ('education', 'শিক্ষা প্রতিষ্ঠান (Education)'), ('site_footer', 'Site Footer (Global Bottom)')], default='all', max_length=50, verbose_name='অ্যাড প্লেসমেন্ট'),
        ),
    ]
