# Generated by Django 6.0.5 on 2026-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_remove_appconfiguration_show_admob_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='admob_frequency',
            field=models.PositiveIntegerField(default=3, verbose_name='ইন্টারস্টেশিয়াল অ্যাড ফ্রিকোয়েন্সি (ক্লিক)'),
        ),
    ]
