# Generated by Django 6.0.5 on 2026-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_alter_appconfiguration_admob_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='fraud_20m_limit',
            field=models.IntegerField(default=5, verbose_name='Fraud: Click Limit (20 Mins)'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='fraud_2h_limit',
            field=models.IntegerField(default=10, verbose_name='Fraud: Click Limit (2 Hours)'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='fraud_block_hours',
            field=models.IntegerField(default=2, verbose_name='Fraud: Block Duration (Hours)'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='admob_frequency',
            field=models.PositiveIntegerField(default=3, verbose_name='অ্যাডমোব ফ্রিকোয়েন্সি'),
        ),
    ]
