# Generated by Django 6.0.5 on 2026-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_appconfiguration_fraud_20m_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='fraud_20m_window',
            field=models.IntegerField(default=20, verbose_name='Fraud: Window 1 (Minutes)'),
        ),
        migrations.AddField(
            model_name='appconfiguration',
            name='fraud_2h_window',
            field=models.IntegerField(default=120, verbose_name='Fraud: Window 2 (Minutes)'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='fraud_20m_limit',
            field=models.IntegerField(default=5, verbose_name='Fraud: Limit 1 (Clicks)'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='fraud_2h_limit',
            field=models.IntegerField(default=10, verbose_name='Fraud: Limit 2 (Clicks)'),
        ),
    ]
